### ISSUE TITLE
Per word coloring on textInputs

### ISSUE THREAD

**Issue by mundusnine** [armory3d/zui#108]
Have a way to color word per word to have a code editor like feel(probably out of scope of this project).

Their could be issues with implementing this (performance wise). Because I imagine that we would have to create a handle per word ? Am I wrong in my thinking ? From what I read we would have to have a handle with .text be a word and a TEXT_COL overrided.

We could maybe pass to textareas or textinputs an array of typedef Words = {
    var word:String;
    var color:kha.Color;
}
Anyways insight into this would be interesting( as this would override the need for using external code editors).

**Comment by solarane** [comment]
"Per-word" seems to have some strange implications? Per-character would probably be a more accurate way to describe this. Per-word seems to imply that zui would somehow handle word boundary checking for us, which we would neither need nor want.

Haven't written Haxe in quite some time but assuming the following from your original issue is valid Haxe:
```haxe
typedef CharacterGroup = {
	var word:String;
	var color:kha.Color;
}
```

Then we could pass an `Array<CharacterGrop>` instead of a `String` to our texts. Considering it's just the per-glyph tint that will need to be changed, I assume performance-wise it won't be too big of a deal.

This would definitely be an interesting feature, +1

**Comment by mundusnine** [comment]
Per char doesn't really make sense. char = one letter/character. word = whole word say "class" to be colored blue. We would actually need to handle word boundary before passing the string array to the ui.textarea. For the word boundary we could just split the string array using the space char as a delimiter.

Another way of doing it would be to make it so the textarea would be able to have a styling map that would contain a string as a key and the resulting color as a value. The textarea/textinput(because in reality the textarea uses textinput) would then see if a word exists in the map, if it doesn't it draws normally. If it does it draws with the color saved in the map.

**Comment by solarane** [comment]
If we (the users) are doing the word boundary checking, all zui would need to do is implement per-char (per-glyph) coloring. :P I really don't like your new suggested approach because it's not nearly as flexible as just doing per-glyph coloring.

With my limited knowledge of graphics programming, different tints should be totally batchable. Implementing per-glyph coloring (and, thereby, per-word coloring) might involve looking into how Kha drawString works.

**Comment by luboslenco** [comment]
I have added a barebones way for text coloring at https://github.com/armory3d/zui/commit/97e3e2a0737d6b834e4dcb651950e8b16c8c712c. Unfortunately it is not as versatile as proposed in this thread, but was the easiest to implement for now.

Example usage:
https://github.com/luboslenco/armorpad/blob/main/Assets/text_coloring.json
https://github.com/luboslenco/armorpad/blob/main/Sources/Main.hx#L77
