### ISSUE TITLE
Typing in text input do not stop the event to be propagated to the game

### ISSUE THREAD

**Issue by wighawag** [armory3d/zui#31]
While I type text in a zui text input, the keys are still propagated in kha resulting in things hapenning while I type.

I guess this needs some support from kha to stop propagation (a la javascript?)

**Comment by luboslenco** [comment]
You should be able to query`Zui.isTyping ` to stop the propagation:
https://github.com/armory3d/zui/blob/master/Sources/zui/Zui.hx#L21

**Comment by wighawag** [comment]
Cool, that should solve my use case. Unfortunately it make the game code dependent on zui.
I wonder if we could implement something in Kha but I am not sure it has its place there

**Comment by sh-dave** [comment]
It doesn't IMO, Kha should only provide you with the very basic abstraction for everything (mouse moved here, key was pressed there). Adding something like an eventhandler (i want to bubble/cancel events) is out of scope there or we end up with something like flash.

Isn't your code tied to zui anyways as that's the nature of immediate mode?
A quick workaround would be to just add a bool somewhere in your current logic code, update that with the zui.isTyping value, and then rely on that bool instead of the zui value?

**Comment by wighawag** [comment]
I agree, though I was not thinking of a full event handler system but just a way to allow for stopping further listener to be called. But again, this probably add unnecessary complexity for something not necessary (at least for that case)

I ll use your approach, this is actually  how I update every values via zui anyway.

Thanks
