### ISSUE TITLE
force redraw when value change from the exterior

### ISSUE THREAD

**Issue by wighawag** [armory3d/zui#33]
I want the UI not only to provide a mechanism to change values but also to show that values even when it is modified from outside the UI

Currently I set 
```
handle.value = <newValues>
````

and I need to do
```
windowHandle.redraws = 2;
```

maybe setting valuye on a handle should set redraws to 2 to itself and all its ancestors

**Comment by sangohan** [comment]
i don't think setting a value should cause a redraw, but rather, the application using this lib should control the redraw (that is, the render frame method in your app). Otherwise, if you updated multiple values externally outside of the render frame method, how does the lib "choose" when to do the redraw?

**Comment by luboslenco** [comment]
Keeping the redraws a bit more conservative for now, so specifying `windowHandle.redraws = 2;` is still needed.
